sudo: false

cache:
    directories:
        - $HOME/.ivy2/cache
        - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

language: scala

scala:
    - 2.11.7
jdk:
    - oraclejdk8

addons:
    apt:
        packages:
            - oracle-java8-installer